/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Card: { // root type
    hint: string; // String!
    id: number; // Int!
    question: string; // String!
    response: string; // String!
    title: string; // String!
  }
  Collection: { // root type
    author: string; // String!
    authorEmail: string; // String!
    description: string; // String!
    id: number; // Int!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email: string; // String!
    name: string; // String!
    password: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Card: { // field return type
    hint: string; // String!
    id: number; // Int!
    question: string; // String!
    response: string; // String!
    title: string; // String!
  }
  Collection: { // field return type
    author: string; // String!
    authorEmail: string; // String!
    description: string; // String!
    id: number; // Int!
    title: string; // String!
  }
  Mutation: { // field return type
    createCard: NexusGenRootTypes['Card']; // Card!
    createCollection: NexusGenRootTypes['Collection']; // Collection!
    deleteCard: NexusGenRootTypes['Card']; // Card!
    deleteCollection: NexusGenRootTypes['Collection']; // Collection!
    updateCard: NexusGenRootTypes['Card']; // Card!
    updateCollection: NexusGenRootTypes['Collection']; // Collection!
  }
  Query: { // field return type
    allCards: NexusGenRootTypes['Card'][]; // [Card!]!
    allCollections: NexusGenRootTypes['Collection'][]; // [Collection!]!
  }
  User: { // field return type
    email: string; // String!
    name: string; // String!
    password: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Card: { // field return type name
    hint: 'String'
    id: 'Int'
    question: 'String'
    response: 'String'
    title: 'String'
  }
  Collection: { // field return type name
    author: 'String'
    authorEmail: 'String'
    description: 'String'
    id: 'Int'
    title: 'String'
  }
  Mutation: { // field return type name
    createCard: 'Card'
    createCollection: 'Collection'
    deleteCard: 'Card'
    deleteCollection: 'Collection'
    updateCard: 'Card'
    updateCollection: 'Collection'
  }
  Query: { // field return type name
    allCards: 'Card'
    allCollections: 'Collection'
  }
  User: { // field return type name
    email: 'String'
    name: 'String'
    password: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createCard: { // args
      hint: string; // String!
      question: string; // String!
      response: string; // String!
      title: string; // String!
    }
    createCollection: { // args
      authorEmail: string; // String!
      description: string; // String!
      title: string; // String!
    }
    deleteCard: { // args
      id: number; // Int!
    }
    deleteCollection: { // args
      id: number; // Int!
    }
    updateCard: { // args
      hint?: string | null; // String
      id: number; // Int!
      question?: string | null; // String
      response?: string | null; // String
      title?: string | null; // String
    }
    updateCollection: { // args
      description?: string | null; // String
      id: number; // Int!
      title?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}